In [3]:
%pip install numpy #numpy install

  Using cached numpy-1.19.1-cp38-cp38-macosx_10_9_x86_64.whl (15.3 MB)
You should consider upgrading via the '/usr/local/Cellar/jupyterlab/2.2.0/libexec/bin/python3.8 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# 용어 정리
### 1. axis : 각 차원, 축
### 2. rank : 축의 개수 = axis의 개수
### 3. shape : 축 길이 = 배열의 크기
### 4. size : 전체 원소의 개수(모든 축의 곱)

In [6]:
np.zeros(5) #np.zeros(n) : 0으로 채워진 n개의 요소를 갖는 배열 생성

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3, 4)) #np.zeros((n, m)) : 0으로 채워진 n행, m열로 이루어진 배열 생성

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
a.shape #.shape : 배열의 축의 길이(배열의 크기)

(3, 4)

In [10]:
a.ndim #.ndim : 축(axis)의 개수

2

In [11]:
a.size #.size : 요소의 개수

12

# N-차원 배열
### 임의의 rank 수를 가진 다차원 배열
### (rank, row, column)

In [13]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Numpy 배열의 타입은 ndarray
### ndarray를 만들 수 있는 다양한 numpy 함수

In [16]:
np.ones((3, 4)) #1로 채움

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.full((3,4), np.pi) #3개의 행, 4개의 열을 파이로 채움

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [18]:
np.array([[1, 2, 3, 4], [10, 20, 30, 40]]) #파이썬의 리스트를 사용하여 ndarray를 초기화

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [24]:
np.arange(1, 5) #.arange(n, m) : n이상 m미만을 객체로 가짐

array([1, 2, 3, 4])

# Random은 ndarray를 랟넘한 값으로 초기화 할 수 있는 함수들이 존재

In [4]:
np.random.rand(3, 4) #0과 1 사이의 부동소수로 3X4 행렬 초기화

array([[0.27623482, 0.16758058, 0.293664  , 0.43457739],
       [0.76629137, 0.20732991, 0.6016397 , 0.66019078],
       [0.18437279, 0.73674644, 0.66423894, 0.2359276 ]])

In [5]:
np.random.randn(3, 4) #평균이 0이고 분산이 1인 일변량 정규분포에서 샘플링한 랜덤한 부동소수로 3X4 행렬 초기화

array([[-0.11476725, -0.01138424,  0.69947489,  0.83900635],
       [-1.00993241, -0.65907801, -1.40474042,  0.00988173],
       [ 0.09316515,  1.80835319,  1.08614469, -0.61427545]])

# 함수를 사용하여 ndarray를 초기화할 수 있음

In [6]:
def my_function(z, y, x): #함수 선언
    return x * y + z

In [9]:
np.fromfunction(my_function, (3, 2, 10)) # 함수 my_function은 원소마다 호출되는 것이 아니라 단 한 번 호출됨

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],

       [[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
        [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]])

# 배열 데이터
### ndarray는 모든 원속가 동일한 타입을 가짐
### dtype : 데이터 타입 출력
### itemsize : 각 아이템의 크기를 반환
### 데이터 타입
#### int64, float64, uint8, complex64 등 존재

In [10]:
c = np.arange(1, 5)
print(c.dtype, c)

int64 [1 2 3 4]


In [11]:
c = np.arange(1.0, 5.0)
print(c.dtype, c)

float64 [1. 2. 3. 4.]


In [13]:
e = np.arange(1, 5, dtype=np.complex64)
e.itemsize

8

# 배열 크기 변경
### ndarray의 shape 속성을 지정하여 크기를 바꿀 수 있음
### reshape 함수를 사용하여 동일한 데이터를 가리키는 새로운  ndarray 객체를 반환
### revel 함수는 동일한 데이터를 가리키는 새로우 1차원 ndarray를 반환

In [24]:
g = np.arange(24)
print(g)
print("rank :", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
rank : 1


In [26]:
g.shape = (6, 4) #6X4 형태로 변경
print(g)
print("rank :", g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
rank : 2


In [27]:
g.shape = (2, 3, 4) #2X3X4 형태로 변경
print(g)
print("rank", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
rank 3


In [29]:
g2 = g.reshape(4, 6)
print(g2)
print("rank :", g2.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
rank : 2


In [30]:
g2[1, 2] = 999 #1행 2열의 원소를 999로 변경
g2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7, 999,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [31]:
g #g2에서 변경된 원소와 상응하는 g의 내용 또한 수정됨

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [999,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [33]:
g.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# 브로드캐스팅
### Numpy는 동일한 크기의 배열을 기대하지만, 그렇지 않은 경우 브로드캐스팅 규칙을 적용
### 1. 배열의 rank가 동일하지 않으면 rank가 맞을 때 까지 rank가 작은 배열 앞에 1을 추가
### 2. 특정 차원이 1인 배열은 그 차원에서 크기가 가장 큰 배열의 크기에 맞춰 동작, 원소가 차원을 따라 반복
### 3. 규칙1, 2를 적용했을 때 모든 배열의 크기가 맞아야함