In [3]:
%pip install numpy #numpy install

  Using cached numpy-1.19.1-cp38-cp38-macosx_10_9_x86_64.whl (15.3 MB)
You should consider upgrading via the '/usr/local/Cellar/jupyterlab/2.2.0/libexec/bin/python3.8 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

# 용어 정리
### 1. axis : 각 차원, 축
### 2. rank : 축의 개수 = axis의 개수
### 3. shape : 축 길이 = 배열의 크기
### 4. size : 전체 원소의 개수(모든 축의 곱)

In [6]:
np.zeros(5) #np.zeros(n) : 0으로 채워진 n개의 요소를 갖는 배열 생성

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3, 4)) #np.zeros((n, m)) : 0으로 채워진 n행, m열로 이루어진 배열 생성

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
a.shape #.shape : 배열의 축의 길이(배열의 크기)

(3, 4)

In [10]:
a.ndim #.ndim : 축(axis)의 개수

2

In [11]:
a.size #.size : 요소의 개수

12

# N-차원 배열
### 임의의 rank 수를 가진 다차원 배열
### (rank, row, column)

In [13]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Numpy 배열의 타입은 ndarray
### ndarray를 만들 수 있는 다양한 numpy 함수

In [16]:
np.ones((3, 4)) #1로 채움

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.full((3,4), np.pi) #3개의 행, 4개의 열을 파이로 채움

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [18]:
np.array([[1, 2, 3, 4], [10, 20, 30, 40]]) #파이썬의 리스트를 사용하여 ndarray를 초기화

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [24]:
np.arange(1, 5) #.arange(n, m) : n이상 m미만을 객체로 가짐

array([1, 2, 3, 4])